# Generated by Django 2.2.28 on 2023-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testiop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testinghj', models.BigIntegerField()),
            ],
        ),
    ]
