# Generated by Django 2.2.28 on 2023-04-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testiop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest', models.BigIntegerField()),
            ],
        ),
    ]
